CLEAR
set talk off
CLOSE ALL
SELE 0
USE TPNF ORDER P_TIPO
SELE 0
USE CLIEN ORDER P_CGC 
SELE 0
USE CABECNF 
SET FILTER TO CANCELADA = .F.
SET RELA TO TIPNF INTO TPNF

GO TOP
DO WHILE ! EOF()
  IF !EOF('TPNF') .AND. TPNF->VENDA = 'S' THEN
    SELE CABECNF
    IF EMPTY(REGIAO) THEN
      IF SEEK(CGC, 'CLIEN') THEN
        REPLACE REGIAO WITH CLIEN->REGIAO
        REPLACE IDREGIAO WITH CLIEN->IDREGIAO
      ELSE
        ? '"' + CGC + '"' + 'Não encontrado'  
      ENDIF
    ENDIF  
    IF EMPTY(VEN) THEN
      IF SEEK(CGC, 'CLIEN') THEN
        REPLACE VEN    WITH CLIEN->VEN
        REPLACE IDREPR WITH CLIEN->IDREPR
      ELSE
        ? '"' + CGC + '"' + 'Não encontrado'  
      ENDIF
    ENDIF  
  ENDIF  
  SELE CABECNF
  SKIP
ENDDO
