@01, 01 SAY 'Pedido:         Situacao:                 Nome Guerra:'
@02, 01 SAY 'Emissao:          Vend.:       Ped.Rep.:         Data Ped.Rep.:'
@03, 01 SAY 'P.Cli.:         Dt.P.Cli.:          Trans.:                      Entr.:'
@04, 01 SAY 'Tipo NF:     Tab.Precos:       Parc:   Moeda:   Dias:     C.Financ:'
@05, 01 SAY 'D.Cliente:           D.Semanal:               C.Pagto:'
@06, 01 SAY 'No Banco:     No Agencia:                     Percent:'
@08, 01 SAY 'It Ref  T d P Preco Tabela  Quantid  D.Gru Promo Bonus Uni %IPI Pr.Unit.Liqu.' 

=INKEY(0)

*Pedido: 999999  Situacao: XXXXXXXXXXXXXXX Nome Guerra: XXXXXXXXXXXXXXX 
*Emissao: 99/99/99 Vend.: 99999 Ped.Rep.: XXXXXXX Data Ped.Rep.: 99/99/99       |
*P.Cli.: XXXXXXX Dt.P.Cli.: 99/99/99 Trans.: 9999 XXXXXXXXXXXXXXX Entr.: 99/99/99
*Tipo NF: 999 Tab.Precos: 00/00 Parc: 9 Moeda: 9 Dias: XXX C.Financ: 000,0
*D.Cliente: 0,00 0,00 D.Semanal: 0,00          C.Pagto:  99  99  99  99 
*No Banco: 999 No Agencia: 99999               Percent: 999 999 999 999 
